name: Read Versions

on:
  workflow_call:
    outputs:
      zig-version:
        description: "Zig version"
        value: ${{ jobs.read.outputs.zig-version }}
      zmin-version:
        description: "Zmin version"
        value: ${{ jobs.read.outputs.zmin-version }}

jobs:
  read:
    runs-on: ubuntu-latest
    outputs:
      zig-version: ${{ steps.versions.outputs.zig }}
      zmin-version: ${{ steps.versions.outputs.zmin }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/versions.json
      
      - name: Read versions
        id: versions
        run: |
          echo "zig=$(jq -r '.zig' .github/versions.json)" >> $GITHUB_OUTPUT
          echo "zmin=$(jq -r '.zmin' .github/versions.json)" >> $GITHUB_OUTPUT